# This is a workflow to build and publish the docker image to dockerhub
name: Build-Publish

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_iiot:
    runs-on: ubuntu-latest
    name: Build and push iiot on latest version
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push iiot image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build -f secondary-versions/iiot/Dockerfile -t bwdesigngroup/ignition-docker-iiot:8.1.21 --build-arg IGNITION_VERSION=8.1.21 secondary-versions/iiot; docker push bwdesigngroup/ignition-docker-iiot:8.1.21

  build_mes:
    runs-on: ubuntu-latest
    name: Build and push mes on latest supported version
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push mes image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build -f secondary-versions/mes/Dockerfile -t bwdesigngroup/ignition-docker-mes:8.1.20 --build-arg IGNITION_VERSION=8.1.20 secondary-versions/mes; docker push bwdesigngroup/ignition-docker-mes:8.1.20

  build_pre_8_1_17:
    runs-on: ubuntu-latest
    name: Build and push pre-8.1.17 versions

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push pre-8.1.17
        env:
          DOCKER_BUILDKIT: 1
        run: |
          for i in $(seq 13 16); do docker build -t bwdesigngroup/ignition-docker:8.1.$i -f secondary-versions/pre-8-1-17/Dockerfile --build-arg IGNITION_VERSION=8.1.$i .; docker push bwdesigngroup/ignition-docker:8.1.$i; done

  build_current:
    runs-on: ubuntu-latest

    name: Build and push current versions

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push current versions
        env:
          DOCKER_BUILDKIT: 1
        run: |
          for i in $(seq 17 21); do docker build -t bwdesigngroup/ignition-docker:8.1.$i --build-arg IGNITION_VERSION=8.1.$i .; docker push bwdesigngroup/ignition-docker:8.1.$i; done
