name: Build Current

on:
  workflow_dispatch:

jobs:
  build-current:
    strategy:
      matrix:
        patch-version: [17,18,19,20,21,22]
    uses: .github/workflows/setup-docker-env.yml@HEAD
    with:
      PATCH_VERSION: ${{ matrix.patch-version }}
      files: ./docker-bake.hcl
      targets: current
      push: true

  build-mes:
    strategy:
      matrix:
        patch-version: [20]
    uses: .github/workflows/setup-docker-env.yml@HEAD
    with:
      PATCH_VERSION: ${{ matrix.patch-version }}
      files: ./docker-bake.hcl
      targets: mes
      push: true
  
  build-iiot:
    strategy:
      matrix:
        patch-version: [21]
    uses:  .github/workflows/setup-docker-env.yml@HEAD
    with:
      PATCH_VERSION: ${{ matrix.patch-version }}
      files: ./docker-bake.hcl
      targets: iiot
      push: true
