name: Build Current

on:
  workflow_dispatch:

jobs:
  build-current:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        patch-version: [17,18,19,20,21,22]
    steps:
      - name: Setup
        uses: design-group/ignition-docker/.github/workflows/setup-docker-env.yml@master
      - name: Build
        uses: docker/bake-action@v2.3.0
        env:
          PATCH_VERSION: ${{ matrix.patch-version }}
        with:
          files: ./docker-bake.hcl
          targets: current
          push: true


  build-mes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        patch-version: [20]
    steps:
      - name: Setup
        uses: design-group/ignition-docker/.github/workflows/setup-docker-env.yml@master
      - name: Build
        uses: docker/bake-action@v2.3.0
        env:
          PATCH_VERSION: ${{ matrix.patch-version }}
        with:
          files: ./docker-bake.hcl
          targets: mes
          push: true

  build-iiot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        patch-version: [21]
    steps:
      - name: Setup
        uses: design-group/ignition-docker/.github/workflows/setup-docker-env.yml@master
      - name: Build
        uses: docker/bake-action@v2.3.0
        env:
          PATCH_VERSION: ${{ matrix.patch-version }}
        with:
          files: ./docker-bake.hcl
          targets: iiot
          push: true