name: Build Current

on:
  workflow_dispatch:

jobs:
  build-current:
    strategy:
      matrix:
        patch-version: [17,18,19,20,21,22]
    uses: ./.github/workflows/setup-docker-env.yml
    with:
      PATCH_VERSION: ${{ matrix.patch-version }}
      TARGETS: current
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}

  build-mes:
    strategy:
      matrix:
        patch-version: [20]
    uses: ./.github/workflows/setup-docker-env.yml
    with:
      PATCH_VERSION: ${{ matrix.patch-version }}
      TARGETS: mes
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  
  
  build-iiot:
    strategy:
      matrix:
        patch-version: [21]
    uses:  ./.github/workflows/setup-docker-env.yml
    with:
      PATCH_VERSION: ${{ matrix.patch-version }}
      TARGETS: iiot
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
