name: "Setup Docker Build Environment"

on:
  workflow_call:
    inputs:
      PATCH_VERSION:
        description: "Patch version to build"
        required: true
        type: number

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: QEMU Setup
        id: qemu
        uses: docker/setup-qemu-action@v2.1.0
        with:
          image: tonistiigi/binfmt:qemu-v6.2.0
          platforms: linux/amd64,linux/arm64,linux/arm/v7
      - name: Buildx Setup
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build
        uses: docker/bake-action@v2.3.0
        env:
          PATCH_VERSION: ${{ inputs.PATCH_VERSION }}
     